# Classificação de imagens com openCV e tensorflow
- (RNA)

## Libs

In [21]:
import cv2
import numpy as np
import os 
import zipfile 
from matplotlib import pyplot as plt 
import pandas as pd 
import seaborn as sns 
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler

In [2]:
tf.__version__

'2.12.0'

## Extração dos dados não estruturados

In [3]:
# Extração dos pixels da imagem
path = '/home/eric/projetos pessoais/computer-vision/Visão Computacional Guia Completo/Datasets/homer_bart_1.zip'
zip_obj = zipfile.ZipFile(path, mode='r')
zip_obj.extractall('./')
zip_obj.close()

In [4]:
diretorio = '/home/eric/projetos pessoais/computer-vision/notebooks/homer_bart_1'

arquivos = [os.path.join(diretorio, f) for f in sorted(os.listdir(diretorio))]

In [5]:
print(arquivos)

['/home/eric/projetos pessoais/computer-vision/notebooks/homer_bart_1/.DS_Store', '/home/eric/projetos pessoais/computer-vision/notebooks/homer_bart_1/bart1.bmp', '/home/eric/projetos pessoais/computer-vision/notebooks/homer_bart_1/bart10.bmp', '/home/eric/projetos pessoais/computer-vision/notebooks/homer_bart_1/bart100.bmp', '/home/eric/projetos pessoais/computer-vision/notebooks/homer_bart_1/bart101.bmp', '/home/eric/projetos pessoais/computer-vision/notebooks/homer_bart_1/bart102.bmp', '/home/eric/projetos pessoais/computer-vision/notebooks/homer_bart_1/bart103.bmp', '/home/eric/projetos pessoais/computer-vision/notebooks/homer_bart_1/bart104.bmp', '/home/eric/projetos pessoais/computer-vision/notebooks/homer_bart_1/bart105.bmp', '/home/eric/projetos pessoais/computer-vision/notebooks/homer_bart_1/bart106.bmp', '/home/eric/projetos pessoais/computer-vision/notebooks/homer_bart_1/bart108.bmp', '/home/eric/projetos pessoais/computer-vision/notebooks/homer_bart_1/bart109.bmp', '/home/e

## Pré-processamento

In [6]:
# tratamento de imagens 
largura = 128
altura = 128

In [7]:
# pixels da imagem
imagens = []
# classes homer e bart
classes = []

In [8]:
for imagem_caminho in arquivos:
    #print(imagem_caminho)
    try:

        imagem = cv2.imread(imagem_caminho)
        # altura e largura
        (h, w) = imagem.shape[:2]
    except:
        continue

    imagem = cv2.resize(imagem, (largura, altura))
    imagem = cv2.cvtColor(imagem , cv2.COLOR_BGR2GRAY)
    #plt.imshow(imagem)
    #plt.show()

    # converter de matriz para vetor
    imagem =  imagem.ravel()
    #print(imagem.shape)
    # add na lista de imagens
    imagens.append(imagem)
    # add classes
    nome_imagem = os.path.basename(os.path.normpath(imagem_caminho))
    #print(nome_imagem)
    if nome_imagem.startswith('b'):
        classe = 0
    else:
        classe = 1
    classes.append(classe)
    #print(classe)


In [9]:
# exemplo bart
imagens[0], classes[0]

(array([255, 255, 255, ..., 255, 255, 255], dtype=uint8), 0)

In [10]:
# exemplo homer
imagens[200], classes[200]

(array([255, 255, 255, ..., 255, 255, 255], dtype=uint8), 1)

## Split inicial

In [11]:
X = np.asarray(imagens)
y = np.asarray(classes)

In [12]:
X.shape

(269, 16384)

In [13]:
y.shape

(269,)

In [19]:
np.unique(y, return_counts=True)

(array([0, 1]), array([160, 109]))

## Normalização dos dados

In [22]:
scaler = MinMaxScaler()

In [24]:
scaler.fit(X)
X = scaler.transform(X)

## Divisão treino e teste